### PR TITLE
feat: add auto-detection of potentially renamed columns

### PR DESCRIPTION
**Pull request by AllenAnthes**
This PR adds functionality to detect if a migration contains potentially renamed columns.  It does this by:

- grouping all diffs by the table they belong to
- finding all diffs that are removing or adding a row
- checking if there are a pair of add/remove diffs that, other than the name, have the same attributes

If a potential column rename is detected the user is then asked if it's actually a rename.  If yes, then a `columnRename` action is added and the add/remove diffs are removed.

image

### CODE REVIEW

**Comment by MRVMV** [comment]
Thanks for PR :)
I hope I was not a little busy in last days to merge it
btw i have read the edits but i cant try them a lot so i will trust you 😂😂

**Comment by MRVMV** [comment]
But we should make the same for index
and i think we can remove the extra package inquirer and go with yargs
maybe we also can remove object-hash
adding a parameter to always rename without asking and finally add auto renames for just changing letters or plurals
a lot of them i know 😂
i will be too happy if you can try with them too :)

**Comment by MRVMV** [comment]
oops something wrong here with this
whenever i press y it will delete some other actions as well
i think its filtering all D and N and not only the same names

**Comment by AllenAnthes** [comment]
Whoops, thanks for catching that. Looks like you fixed it in 3.1.1?  

I figure I'll try to add the functionality for indices and table names after we test the current changes out in the wild for a bit.

**Comment by MRVMV** [comment]
Yeah!, @AllenAnthes then i will open a new issue to track that one :) and surely mention you there

**Pull request merged**
